/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import controller.Controller;
import controller.TimeFormatter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.PlainDocument;
import model.Servidores;

/**
 *
 * @author Diego Dias
 */
public class AddServersUI extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form AddServersUI
     */
    public AddServersUI() {
        Controller ctrl = Controller.getInstance();

        initComponents();
        ctrl.frAddServersUICreateTable(this);
        ctrl.frAddServersUIRefreshTable(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dAddServer = new javax.swing.JDialog();
        tfNomeAtendente = new javax.swing.JTextField();
        lbNomeAtendente = new javax.swing.JLabel();
        lbInicioExpediente = new javax.swing.JLabel();
        lbFinalExpdiente = new javax.swing.JLabel();
        btAddServerDialogSalvar = new javax.swing.JButton();
        lbSaidaAlmoco = new javax.swing.JLabel();
        lbRetornoAlmoco = new javax.swing.JLabel();
        tfInicioExpediente = new javax.swing.JTextField();
        tfFinalExpediente = new javax.swing.JTextField();
        tfSaidaAlmoco = new javax.swing.JTextField();
        tfRetornoAlmoco = new javax.swing.JTextField();
        tfTempoAtendimento = new javax.swing.JTextField();
        chbAtivo = new javax.swing.JCheckBox();
        lbTempoAtendimento = new javax.swing.JLabel();
        dEditServer = new javax.swing.JDialog();
        tfNomeAtendente1 = new javax.swing.JTextField();
        lbNomeAtendente1 = new javax.swing.JLabel();
        lbInicioExpediente1 = new javax.swing.JLabel();
        lbFinalExpdiente1 = new javax.swing.JLabel();
        btAddServerDialogAtualizar = new javax.swing.JButton();
        lbSaidaAlmoco1 = new javax.swing.JLabel();
        lbRetornoAlmoco1 = new javax.swing.JLabel();
        tfInicioExpediente1 = new javax.swing.JTextField();
        tfFinalExpediente1 = new javax.swing.JTextField();
        tfSaidaAlmoco1 = new javax.swing.JTextField();
        tfRetornoAlmoco1 = new javax.swing.JTextField();
        tfTempoAtendimento1 = new javax.swing.JTextField();
        chbAtivo1 = new javax.swing.JCheckBox();
        lbTempoAtendimento1 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        spTbAtendentes = new javax.swing.JScrollPane();
        tbAtendentes = new javax.swing.JTable() {
            private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };

        dAddServer.setTitle("Adicionar Atendente");
        dAddServer.setModal(true);

        tfNomeAtendente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfNomeAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeAtendenteActionPerformed(evt);
            }
        });

        lbNomeAtendente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeAtendente.setText("Nome do atendente:");

        lbInicioExpediente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbInicioExpediente.setText("Inicio do expediente:");

        lbFinalExpdiente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFinalExpdiente.setText("Final do expediente:");

        btAddServerDialogSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btAddServerDialogSalvar.setText("Salvar");
        btAddServerDialogSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddServerDialogSalvarActionPerformed(evt);
            }
        });

        lbSaidaAlmoco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSaidaAlmoco.setText("Saída para almoço:");

        lbRetornoAlmoco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRetornoAlmoco.setText("Retorno do almoço:");

        tfInicioExpediente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfFinalExpediente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfSaidaAlmoco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfRetornoAlmoco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfTempoAtendimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        chbAtivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbAtivo.setSelected(true);
        chbAtivo.setText("Permitir agendamentos");
        chbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAtivoActionPerformed(evt);
            }
        });

        lbTempoAtendimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTempoAtendimento.setText("Tempo de atendimento:");

        javax.swing.GroupLayout dAddServerLayout = new javax.swing.GroupLayout(dAddServer.getContentPane());
        dAddServer.getContentPane().setLayout(dAddServerLayout);
        dAddServerLayout.setHorizontalGroup(
            dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dAddServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAddServerDialogSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dAddServerLayout.createSequentialGroup()
                        .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbRetornoAlmoco)
                            .addComponent(lbSaidaAlmoco)
                            .addComponent(lbFinalExpdiente)
                            .addComponent(lbInicioExpediente)
                            .addComponent(lbNomeAtendente)
                            .addComponent(lbTempoAtendimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfInicioExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSaidaAlmoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRetornoAlmoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFinalExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTempoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dAddServerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chbAtivo)
                .addGap(44, 44, 44))
        );

        dAddServerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfFinalExpediente, tfInicioExpediente, tfNomeAtendente, tfRetornoAlmoco, tfSaidaAlmoco, tfTempoAtendimento});

        dAddServerLayout.setVerticalGroup(
            dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAddServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeAtendente)
                    .addComponent(tfNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInicioExpediente)
                    .addComponent(tfInicioExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFinalExpdiente)
                    .addComponent(tfFinalExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSaidaAlmoco)
                    .addComponent(tfSaidaAlmoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRetornoAlmoco)
                    .addComponent(tfRetornoAlmoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTempoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTempoAtendimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chbAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAddServerDialogSalvar)
                .addGap(6, 6, 6))
        );

        dEditServer.setTitle("Editar Atendente");
        dEditServer.setModal(true);

        tfNomeAtendente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfNomeAtendente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeAtendente1ActionPerformed(evt);
            }
        });

        lbNomeAtendente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeAtendente1.setText("Nome do atendente:");

        lbInicioExpediente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbInicioExpediente1.setText("Inicio do expediente:");

        lbFinalExpdiente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFinalExpdiente1.setText("Final do expediente:");

        btAddServerDialogAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btAddServerDialogAtualizar.setText("Atualizar");
        btAddServerDialogAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddServerDialogAtualizarActionPerformed(evt);
            }
        });

        lbSaidaAlmoco1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSaidaAlmoco1.setText("Saída para almoço:");

        lbRetornoAlmoco1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRetornoAlmoco1.setText("Retorno do almoço:");

        tfInicioExpediente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfFinalExpediente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfSaidaAlmoco1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfRetornoAlmoco1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfTempoAtendimento1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        chbAtivo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbAtivo1.setSelected(true);
        chbAtivo1.setText("Permitir agendamentos");

        lbTempoAtendimento1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTempoAtendimento1.setText("Tempo de atendimento:");

        javax.swing.GroupLayout dEditServerLayout = new javax.swing.GroupLayout(dEditServer.getContentPane());
        dEditServer.getContentPane().setLayout(dEditServerLayout);
        dEditServerLayout.setHorizontalGroup(
            dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dEditServerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chbAtivo1)
                .addGap(44, 44, 44))
            .addGroup(dEditServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dEditServerLayout.createSequentialGroup()
                        .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbRetornoAlmoco1)
                            .addComponent(lbSaidaAlmoco1)
                            .addComponent(lbFinalExpdiente1)
                            .addComponent(lbInicioExpediente1)
                            .addComponent(lbNomeAtendente1)
                            .addComponent(lbTempoAtendimento1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfInicioExpediente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSaidaAlmoco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRetornoAlmoco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomeAtendente1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFinalExpediente1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTempoAtendimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btAddServerDialogAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        dEditServerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfFinalExpediente1, tfInicioExpediente1, tfNomeAtendente1, tfRetornoAlmoco1, tfSaidaAlmoco1, tfTempoAtendimento1});

        dEditServerLayout.setVerticalGroup(
            dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dEditServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeAtendente1)
                    .addComponent(tfNomeAtendente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInicioExpediente1)
                    .addComponent(tfInicioExpediente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFinalExpdiente1)
                    .addComponent(tfFinalExpediente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSaidaAlmoco1)
                    .addComponent(tfSaidaAlmoco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRetornoAlmoco1)
                    .addComponent(tfRetornoAlmoco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dEditServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTempoAtendimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTempoAtendimento1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(chbAtivo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAddServerDialogAtualizar)
                .addContainerGap())
        );

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tbAtendentes.setModel(atendenteTableModel);
        tbAtendentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbAtendentes.getTableHeader().setReorderingAllowed(false);
        tbAtendentes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbAtendentesPropertyChange(evt);
            }
        });
        spTbAtendentes.setViewportView(tbAtendentes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spTbAtendentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spTbAtendentes, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btEditar)
                    .addComponent(btExcluir))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (getTbAtendentes().getSelectedRowCount() > 0) {
            Controller ctrl = Controller.getInstance();
            ctrl.frAddServersUIBtExcluir(this);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        getdAddServer().pack();
        getdAddServer().setVisible(true);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (getTbAtendentes().getSelectedRowCount() > 0) {
            Controller ctrl = Controller.getInstance();
            ctrl.frAddServersUIBtEditar(this);
            dEditServer.pack();
            dEditServer.setVisible(true);
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    }//GEN-LAST:event_formFocusGained

    private void btAddServerDialogSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddServerDialogSalvarActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frAddServersUIBtSalvar(this);
        ctrl.frAddServersUIRefreshTable(this);
    }//GEN-LAST:event_btAddServerDialogSalvarActionPerformed

    private void tfNomeAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeAtendenteActionPerformed

    private void tfNomeAtendente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeAtendente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeAtendente1ActionPerformed

    private void btAddServerDialogAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddServerDialogAtualizarActionPerformed

        Controller ctrl = Controller.getInstance();
        ctrl.frAddServersUIBtAtualizar(this);
        ctrl.frAddServersUIRefreshTable(this);
        dEditServer.dispose();
    }//GEN-LAST:event_btAddServerDialogAtualizarActionPerformed

    private void chbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbAtivoActionPerformed

    private void tbAtendentesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbAtendentesPropertyChange
    }//GEN-LAST:event_tbAtendentesPropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddServerDialogAtualizar;
    private javax.swing.JButton btAddServerDialogSalvar;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JCheckBox chbAtivo;
    private javax.swing.JCheckBox chbAtivo1;
    private javax.swing.JDialog dAddServer;
    private javax.swing.JDialog dEditServer;
    private javax.swing.JLabel lbFinalExpdiente;
    private javax.swing.JLabel lbFinalExpdiente1;
    private javax.swing.JLabel lbInicioExpediente;
    private javax.swing.JLabel lbInicioExpediente1;
    private javax.swing.JLabel lbNomeAtendente;
    private javax.swing.JLabel lbNomeAtendente1;
    private javax.swing.JLabel lbRetornoAlmoco;
    private javax.swing.JLabel lbRetornoAlmoco1;
    private javax.swing.JLabel lbSaidaAlmoco;
    private javax.swing.JLabel lbSaidaAlmoco1;
    private javax.swing.JLabel lbTempoAtendimento;
    private javax.swing.JLabel lbTempoAtendimento1;
    private javax.swing.JScrollPane spTbAtendentes;
    private javax.swing.JTable tbAtendentes;
    private javax.swing.JTextField tfFinalExpediente;
    private javax.swing.JTextField tfFinalExpediente1;
    private javax.swing.JTextField tfInicioExpediente;
    private javax.swing.JTextField tfInicioExpediente1;
    private javax.swing.JTextField tfNomeAtendente;
    private javax.swing.JTextField tfNomeAtendente1;
    private javax.swing.JTextField tfRetornoAlmoco;
    private javax.swing.JTextField tfRetornoAlmoco1;
    private javax.swing.JTextField tfSaidaAlmoco;
    private javax.swing.JTextField tfSaidaAlmoco1;
    private javax.swing.JTextField tfTempoAtendimento;
    private javax.swing.JTextField tfTempoAtendimento1;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel atendenteTableModel = new DefaultTableModel();


    /**
     * @return the tbAtendentes
     */
    public javax.swing.JTable getTbAtendentes() {
        return tbAtendentes;
    }

    /**
     * @return the atendenteTableModel
     */
    public DefaultTableModel getAtendenteTableModel() {
        return atendenteTableModel;
    }

    /**
     * @param atendenteTableModel the atendenteTableModel to set
     */
    public void setAtendenteTableModel(DefaultTableModel atendenteTableModel) {
        this.atendenteTableModel = atendenteTableModel;
    }

    /**
     * @return the spTbAtendentes
     */
    public javax.swing.JScrollPane getSpTbAtendentes() {
        return spTbAtendentes;
    }

    public Servidores getFormAdicionarData() {

        Servidores server = new Servidores();

        server.setName(tfNomeAtendente.getText());
        server.setInicioalmoco(tfSaidaAlmoco.getText());
        server.setFinalalmoco(tfRetornoAlmoco.getText());
        server.setInicioexp(tfInicioExpediente.getText());
        server.setFinalexp(tfFinalExpediente.getText());
        server.setServico(tfTempoAtendimento.getText());
        server.setStatus(chbAtivo.isSelected() ? 'A' : 'I');

        return server;

    }

    public int getSelectedServerId() {

        int serverId;
        int row = getTbAtendentes().getSelectedRow();

        serverId = Integer.parseInt(getAtendenteTableModel().
                getValueAt(row, getAtendenteTableModel().
                findColumn("ID")).
                toString());

        return serverId;

    }

    /**
     * @return the chbAtivo1
     */
    public javax.swing.JCheckBox getChbAtivo1() {
        return chbAtivo1;
    }

    /**
     * @return the tfFinalExpediente1
     */
    public javax.swing.JTextField getTfFinalExpediente1() {
        return tfFinalExpediente1;
    }

    /**
     * @return the tfInicioExpediente1
     */
    public javax.swing.JTextField getTfInicioExpediente1() {
        return tfInicioExpediente1;
    }

    /**
     * @return the tfNomeAtendente1
     */
    public javax.swing.JTextField getTfNomeAtendente1() {
        return tfNomeAtendente1;
    }

    /**
     * @return the tfRetornoAlmoco1
     */
    public javax.swing.JTextField getTfRetornoAlmoco1() {
        return tfRetornoAlmoco1;
    }

    /**
     * @return the tfSaidaAlmoco1
     */
    public javax.swing.JTextField getTfSaidaAlmoco1() {
        return tfSaidaAlmoco1;
    }

    /**
     * @return the tfTempoAtendimento1
     */
    public javax.swing.JTextField getTfTempoAtendimento1() {
        return tfTempoAtendimento1;
    }

    /**
     * @return the dAddServer
     */
    public javax.swing.JDialog getdAddServer() {
        return dAddServer;
    }

    public void cleanFields() {
        tfFinalExpediente.setText("");
        tfInicioExpediente.setText("");
        tfNomeAtendente.setText("");
        tfRetornoAlmoco.setText("");
        tfSaidaAlmoco.setText("");
        tfTempoAtendimento.setText("");
        chbAtivo.setSelected(true);

    }
}
