/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import java.io.IOException;

/**
 *
 * @author Diego Dias
 */
public class AjudaUI extends javax.swing.JPanel {

    /**
     * Creates new form AjudaUI
     */
    public AjudaUI() {
        
//        String text = "";
        initComponents();
        
//        try{
//            FileReader fr = new FileReader("Readme.txt");
//            BufferedReader reader = new BufferedReader(fr);
//            String textLine = "";
//            while(textLine!=null){
//                textLine = reader.readLine();
//                text = text + textLine + "\n";
//            }
//        }catch(Exception ex){
//           text+="Não foi possível encontrar Readme.txt";            
//        }
//
//        
//        
        

     createEditorPane();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spEdAjuda = new javax.swing.JScrollPane();
        epAjuda = new javax.swing.JEditorPane();

        epAjuda.setEditable(false);
        spEdAjuda.setViewportView(epAjuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spEdAjuda)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spEdAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane epAjuda;
    private javax.swing.JScrollPane spEdAjuda;
    // End of variables declaration//GEN-END:variables

      public void createEditorPane() {

        epAjuda.setEditable(false);
        java.net.URL helpURL = AjudaUI.class.getResource("basic.html");
        if (helpURL != null) {
            try {
                epAjuda.setPage(helpURL);
            } catch (IOException e) {
                System.err.println("Attempted to read a bad URL: " + helpURL);
            }
        } else {
            System.err.println("Couldn't find file: basic.html");
        }
    }

}
