/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import controller.Controller;
import javax.swing.SwingUtilities;

/**
 *
 * @author Diego Dias
 */
public class ConfDbUI extends javax.swing.JPanel {

    /**
     * Creates new form ConfDbUI
     */
    public ConfDbUI() {
        
        Controller ctrl = Controller.getInstance();

        initComponents();
        ctrl.frConfigurarUILoadParams(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDbHostname = new javax.swing.JTextField();
        tfDbUsername = new javax.swing.JTextField();
        tfDbPassword = new javax.swing.JPasswordField();
        tfDbName = new javax.swing.JTextField();
        lbDbName = new javax.swing.JLabel();
        lbDbPassword = new javax.swing.JLabel();
        lbDbUsername = new javax.swing.JLabel();
        lbDbHostname = new javax.swing.JLabel();
        lbImpossivelConectar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btAtualizar = new javax.swing.JButton();
        btMenuPrincipal = new javax.swing.JButton();

        setToolTipText("");

        tfDbHostname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfDbHostname.setText("localhost");

        tfDbUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfDbUsername.setText("postgres");

        tfDbPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfDbPassword.setText("detran");

        tfDbName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfDbName.setText("detrandb");

        lbDbName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDbName.setText("Banco:");

        lbDbPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDbPassword.setText("Password:");

        lbDbUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDbUsername.setText("Username:");

        lbDbHostname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDbHostname.setText("Hostname:");

        lbImpossivelConectar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbImpossivelConectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImpossivelConectar.setToolTipText("");
        lbImpossivelConectar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btMenuPrincipal.setText("Menu Principal");
        btMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btMenuPrincipal)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMenuPrincipal)
                    .addComponent(btAtualizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDbName)
                            .addComponent(lbDbHostname)
                            .addComponent(lbDbUsername)
                            .addComponent(lbDbPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDbUsername)
                            .addComponent(tfDbPassword)
                            .addComponent(tfDbHostname)
                            .addComponent(tfDbName, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)))
                    .addComponent(lbImpossivelConectar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDbHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDbHostname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDbUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDbPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDbName)
                    .addComponent(tfDbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lbImpossivelConectar)
                .addGap(18, 75, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuPrincipalActionPerformed
       Controller ctrl = Controller.getInstance();
       ctrl.frConfigurarUIBtMenuPrincipal((ConfigurarUI) SwingUtilities.getWindowAncestor(this));
    }//GEN-LAST:event_btMenuPrincipalActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        
        Controller ctrl = Controller.getInstance();
        ctrl.frConfigurarUISaveParams(this);       
    }//GEN-LAST:event_btAtualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btMenuPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDbHostname;
    private javax.swing.JLabel lbDbName;
    private javax.swing.JLabel lbDbPassword;
    private javax.swing.JLabel lbDbUsername;
    private javax.swing.JLabel lbImpossivelConectar;
    private javax.swing.JTextField tfDbHostname;
    private javax.swing.JTextField tfDbName;
    private javax.swing.JPasswordField tfDbPassword;
    private javax.swing.JTextField tfDbUsername;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tfDbHostname
     */
    public javax.swing.JTextField getTfDbHostname() {
        return tfDbHostname;
    }

    /**
     * @param tfDbHostname the tfDbHostname to set
     */
    public void setTfDbHostname(javax.swing.JTextField tfDbHostname) {
        this.tfDbHostname = tfDbHostname;
    }

    /**
     * @return the tfDbName
     */
    public javax.swing.JTextField getTfDbName() {
        return tfDbName;
    }

    /**
     * @param tfDbName the tfDbName to set
     */
    public void setTfDbName(javax.swing.JTextField tfDbName) {
        this.tfDbName = tfDbName;
    }

    /**
     * @return the tfDbPassword
     */
    public javax.swing.JPasswordField getTfDbPassword() {
        return tfDbPassword;
    }

    /**
     * @param tfDbPassword the tfDbPassword to set
     */
    public void setTfDbPassword(javax.swing.JPasswordField tfDbPassword) {
        this.tfDbPassword = tfDbPassword;
    }

    /**
     * @return the tfDbUsername
     */
    public javax.swing.JTextField getTfDbUsername() {
        return tfDbUsername;
    }

    /**
     * @param tfDbUsername the tfDbUsername to set
     */
    public void setTfDbUsername(javax.swing.JTextField tfDbUsername) {
        this.tfDbUsername = tfDbUsername;
    }

    /**
     * @return the lbImpossivelConectar
     */
    public javax.swing.JLabel getLbImpossivelConectar() {
        return lbImpossivelConectar;
    }
}
