/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import controller.Controller;
import java.awt.Dimension;
import java.awt.Event;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import model.Connector;

/**
 *
 * @author Diego Dias
 */
public class MenuPrincipalUI extends javax.swing.JFrame {

    /**
     * @return the con
     */
    public static Connector getCon() {
        return con;
    }

    /**
     * @param aCon the con to set
     */
    public static void setCon(Connector aCon) {
        con = aCon;
    }

    /**
     * Creates new form InitUI
     */
    public MenuPrincipalUI(Connector con) {
        
        
        initComponents();
        
        if (getCon() == null) {
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Dimension screenSize = toolkit.getScreenSize();
            dLogin.pack();
            int x = (screenSize.width - dLogin.getWidth()) / 2;
            int y = (screenSize.height - dLogin.getHeight()) / 2;
            dLogin.setLocation(x, y);
            dLogin.setVisible(true);
        }
        
        try {
            setCon(con);
            if (getCon().getCon() == null) {
                btCadastrar.setEnabled(false);
                btAcompanhar.setEnabled(false);               
            } else {
                if (getCon().getCon().isClosed()) {
                    btCadastrar.setEnabled(false);
                    btAcompanhar.setEnabled(false);
                } else {
                    Controller ctrl = Controller.getInstance();
                    ctrl.frAnyFrameSetIconImage(this);                 
                    ctrl.frMenuPrincipalControleDeAcesso(this);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipalUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLocationRelativeTo(null);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dLogin = new javax.swing.JDialog();
        btEntrar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        tfUsuario = new javax.swing.JTextField();
        lbUsuario = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        lbFalhaLogin = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btAcompanhar = new javax.swing.JButton();
        btConfigurar = new javax.swing.JButton();
        lbDetran = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();

        dLogin.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dLogin.setTitle("Autenticação");
        dLogin.setIconImage(null);
        dLogin.setModal(true);

        btEntrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        tfUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuarioActionPerformed(evt);
            }
        });

        lbUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbUsuario.setText("Usuário:");

        lbSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSenha.setText("Senha:");

        tfSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSenhaActionPerformed(evt);
            }
        });
        tfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dLoginLayout = new javax.swing.GroupLayout(dLogin.getContentPane());
        dLogin.getContentPane().setLayout(dLoginLayout);
        dLoginLayout.setHorizontalGroup(
            dLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dLoginLayout.createSequentialGroup()
                        .addGroup(dLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dLoginLayout.createSequentialGroup()
                                .addComponent(btEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dLoginLayout.createSequentialGroup()
                                .addComponent(lbUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dLoginLayout.createSequentialGroup()
                                .addComponent(lbSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dLoginLayout.createSequentialGroup()
                        .addComponent(lbFalhaLogin)
                        .addGap(46, 46, 46))))
        );
        dLoginLayout.setVerticalGroup(
            dLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenha)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFalhaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntrar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PhotoScheduler");

        btCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.setToolTipText("");
        btCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCadastrarMouseEntered(evt);
            }
        });
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        btCadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btCadastrarFocusGained(evt);
            }
        });
        btCadastrar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btCadastrarPropertyChange(evt);
            }
        });

        btAcompanhar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAcompanhar.setText("Acompanhar");
        btAcompanhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcompanharActionPerformed(evt);
            }
        });

        btConfigurar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btConfigurar.setText("Configurar");
        btConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfigurarActionPerformed(evt);
            }
        });

        lbDetran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/img/Detran.png"))); // NOI18N

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTitulo.setText("Agendamento de Atendimento");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbDetran)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAcompanhar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, panelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(lbTitulo)
                .addGap(218, 218, 218))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lbDetran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btAcompanhar)
                    .addComponent(btConfigurar)
                    .addComponent(btCadastrar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfigurarActionPerformed
        // TODO add your handling code here:
        ConfigurarUI telaConfigurar = new ConfigurarUI(con);
        dispose();
        telaConfigurar.setVisible(true);
        
    }//GEN-LAST:event_btConfigurarActionPerformed
    
    @SuppressWarnings("empty-statement")
    private void btAcompanharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcompanharActionPerformed
        // TODO add your handling code here:

        dispose();
        AcompanharUI telaAcompanhar = new AcompanharUI(con);
        telaAcompanhar.setVisible(true);
        
    }//GEN-LAST:event_btAcompanharActionPerformed
    
    private void btCadastrarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btCadastrarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarPropertyChange
    
    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastrarUI telaCadastro = new CadastrarUI(con);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btCadastrarActionPerformed
    
    private void btCadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btCadastrarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarFocusGained
    
    private void btCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarMouseEntered
    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed
    
    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        
        Controller ctrl = Controller.getInstance();
        ctrl.frMenuPrincipalLogin(this);
        
    }//GEN-LAST:event_btEntrarActionPerformed
    
    private void tfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuarioActionPerformed
        tfSenha.requestFocus();
    }//GEN-LAST:event_tfUsuarioActionPerformed
    
    private void tfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSenhaActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frMenuPrincipalLogin(this);
    }//GEN-LAST:event_tfSenhaActionPerformed
    
    private void tfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSenhaKeyPressed
        if (evt.getModifiers() == Event.CTRL_MASK) {
            if (evt.getKeyCode() == KeyEvent.VK_C ||
                evt.getKeyCode() == KeyEvent.VK_V) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tfSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void CreateAndShowInitUI(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipalUI(Controller.getCon()).setVisible(true);
            }
        });
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcompanhar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConfigurar;
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btSair;
    private javax.swing.JDialog dLogin;
    private javax.swing.JLabel lbDetran;
    private javax.swing.JLabel lbFalhaLogin;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
    private static Connector con;

    /**
     * @return the tfUsuario
     */
    public javax.swing.JTextField getTfUsuario() {
        return tfUsuario;
    }

    /**
     * @return the tfSenha
     */
    public javax.swing.JPasswordField getTfSenha() {
        return tfSenha;
    }

    /**
     * @return the dLogin
     */
    public javax.swing.JDialog getdLogin() {
        return dLogin;
    }

    /**
     * @return the lbFalhaLogin
     */
    public javax.swing.JLabel getLbFalhaLogin() {
        return lbFalhaLogin;
    }

    /**
     * @return the btAcompanhar
     */
    public javax.swing.JButton getBtAcompanhar() {
        return btAcompanhar;
    }

    /**
     * @return the btCadastrar
     */
    public javax.swing.JButton getBtCadastrar() {
        return btCadastrar;
    }

    /**
     * @return the btConfigurar
     */
    public javax.swing.JButton getBtConfigurar() {
        return btConfigurar;
    }
}
