/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import controller.Controller;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego Dias
 */
public class ServersStatisticsUI extends javax.swing.JPanel {

    /**
     * Creates new form ServersStatisticsUI
     */
    public ServersStatisticsUI() {

        Controller ctrl = Controller.getInstance();

        initComponents();
        ctrl.frServerStatisticsUICreateTable(this);
        ctrl.frServerStatisticsUIRefreshTable(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTbEstatisticas = new javax.swing.JScrollPane();
        tbEstatisticas = new javax.swing.JTable();
        btImprimir = new javax.swing.JButton();
        dcDateChooser = new datechooser.beans.DateChooserCombo();
        lbData = new javax.swing.JLabel();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tbEstatisticas.setModel(estatisticasModel);
        tbEstatisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbEstatisticas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbEstatisticas.getTableHeader().setReorderingAllowed(false);
        spTbEstatisticas.setViewportView(tbEstatisticas);

        btImprimir.setText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        dcDateChooser.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        dcDateChooser.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));
        dcDateChooser.setLocale(new java.util.Locale("pt", "BR", ""));
        dcDateChooser.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        dcDateChooser.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dcDateChooserOnSelectionChange(evt);
            }
        });

        lbData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbData.setText("Data:");

        btAnterior.setText("Anterior");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setText("Próximo");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btImprimir)
                .addContainerGap())
            .addComponent(spTbEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(spTbEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(dcDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btImprimir)
                            .addComponent(btAnterior)
                            .addComponent(btProximo)))
                    .addComponent(lbData))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
      
SimpleDateFormat formatterMonth = new SimpleDateFormat("dd 'de' MMMM'/'yyyy");
        MessageFormat header = new MessageFormat("Relatório de Atendimento: "+
                formatterMonth.format(
                                getDcDateChooser().getSelectedDate().getTime()));
        MessageFormat footer = new MessageFormat("Página {0}");
        try {

            getTbEstatisticas().print(JTable.PrintMode.FIT_WIDTH, header, footer,
                                                 true, null,
                                                 true, null);
        } catch (PrinterException ex) {
            Logger.getLogger(ServersStatisticsUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void dcDateChooserOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dcDateChooserOnSelectionChange
        
        Controller ctrl = Controller.getInstance();
        ctrl.frServerStatisticsUIRefreshTable(this);
    }//GEN-LAST:event_dcDateChooserOnSelectionChange

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        Calendar selectedDate = getDcDateChooser().getSelectedDate();
        selectedDate.add(Calendar.DAY_OF_MONTH, -1);
        getDcDateChooser().setSelectedDate(selectedDate);
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        Calendar selectedDate = getDcDateChooser().getSelectedDate();
        selectedDate.add(Calendar.DAY_OF_MONTH, 1);
        getDcDateChooser().setSelectedDate(selectedDate);
    }//GEN-LAST:event_btProximoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btProximo;
    private datechooser.beans.DateChooserCombo dcDateChooser;
    private javax.swing.JLabel lbData;
    private javax.swing.JScrollPane spTbEstatisticas;
    private javax.swing.JTable tbEstatisticas;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel estatisticasModel = new DefaultTableModel();

    /**
     * @return the dcDateChooser
     */
    public datechooser.beans.DateChooserCombo getDcDateChooser() {
        return dcDateChooser;
    }

    /**
     * @return the lbData
     */
    public javax.swing.JLabel getLbData() {
        return lbData;
    }

    /**
     * @return the tbEstatisticas
     */
    public javax.swing.JTable getTbEstatisticas() {
        return tbEstatisticas;
    }

    /**
     * @return the estatisticasModel
     */
    public DefaultTableModel getEstatisticasModel() {
        return estatisticasModel;
    }

}
