/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import controller.Controller;

/**
 *
 * @author Diego Dias
 */
public class StatisticsUI extends javax.swing.JPanel {

    /**
     * Creates new form StatisticsUI
     */
    public StatisticsUI() {
        
        initComponents();
        jTabbedPaneStatisticsUI.add("Atendimentos",serverStatistics);
        jTabbedPaneStatisticsUI.add("Agendamentos",userStatistics);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneStatisticsUI = new javax.swing.JTabbedPane();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTabbedPaneStatisticsUI.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPaneStatisticsUIComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneStatisticsUI, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneStatisticsUI, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneStatisticsUIComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPaneStatisticsUIComponentShown
    }//GEN-LAST:event_jTabbedPaneStatisticsUIComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        Controller ctrl = Controller.getInstance();
        ctrl.frUserStatisticsUIRefreshTable(userStatistics);
        ctrl.frServerStatisticsUIRefreshTable(serverStatistics);
        
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneStatisticsUI;
    // End of variables declaration//GEN-END:variables
   private ServersStatisticsUI serverStatistics = new ServersStatisticsUI();
   private UserStatisticsUI userStatistics = new UserStatisticsUI();
}
