/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import controller.Controller;
import javax.swing.table.DefaultTableModel;
import model.Usuarios;

/**
 *
 * @author Diego Dias
 */
public class UsuariosUI extends javax.swing.JPanel {

    /**
     * Creates new form UsuariosUI
     */
    public UsuariosUI() {
        Controller ctrl = Controller.getInstance();
        
        initComponents();
        ctrl.frUsuariosUICreateTable(this);
        ctrl.frUsuariosUIRefreshTable(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dAdicionarUsuario = new javax.swing.JDialog();
        lbNomeUsuario = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        tfNomeUsuario = new javax.swing.JTextField();
        tfSenha = new javax.swing.JPasswordField();
        tfLogin = new javax.swing.JTextField();
        chbCadastrar = new javax.swing.JCheckBox();
        chbAcompanhar = new javax.swing.JCheckBox();
        chbConfigurar = new javax.swing.JCheckBox();
        lbVisualizacaoDoUsuario = new javax.swing.JLabel();
        chbAgendamentoPrioritario = new javax.swing.JCheckBox();
        chbAtenderExcluir = new javax.swing.JCheckBox();
        spTbUsuarios = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable() {

            private static final long serialVersionUID = 1L;
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        dAdicionarUsuario.setTitle("Adicionar Usuário");
        dAdicionarUsuario.setModal(true);

        lbNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeUsuario.setText("Nome do usuário:");

        lbLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLogin.setText("Login:");

        lbSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSenha.setText("Senha:");

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        tfNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        chbCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbCadastrar.setText("Cadastrar");

        chbAcompanhar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbAcompanhar.setText("Acompanhar");

        chbConfigurar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbConfigurar.setText("Configurar");
        chbConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbConfigurarActionPerformed(evt);
            }
        });

        lbVisualizacaoDoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbVisualizacaoDoUsuario.setText("Visualização do usuário:");

        chbAgendamentoPrioritario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbAgendamentoPrioritario.setText("Agendamento prioritário");
        chbAgendamentoPrioritario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAgendamentoPrioritarioActionPerformed(evt);
            }
        });

        chbAtenderExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbAtenderExcluir.setText("Excluir");

        javax.swing.GroupLayout dAdicionarUsuarioLayout = new javax.swing.GroupLayout(dAdicionarUsuario.getContentPane());
        dAdicionarUsuario.getContentPane().setLayout(dAdicionarUsuarioLayout);
        dAdicionarUsuarioLayout.setHorizontalGroup(
            dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dAdicionarUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(dAdicionarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAtenderExcluir)
                    .addComponent(chbAgendamentoPrioritario)
                    .addGroup(dAdicionarUsuarioLayout.createSequentialGroup()
                        .addGroup(dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNomeUsuario)
                            .addComponent(lbLogin)
                            .addComponent(lbSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(tfNomeUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSenha)))
                    .addComponent(lbVisualizacaoDoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dAdicionarUsuarioLayout.createSequentialGroup()
                        .addComponent(chbCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbAcompanhar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbConfigurar)))
                .addGap(10, 10, 10))
        );
        dAdicionarUsuarioLayout.setVerticalGroup(
            dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAdicionarUsuarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeUsuario)
                    .addComponent(tfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSenha)
                    .addGroup(dAdicionarUsuarioLayout.createSequentialGroup()
                        .addGroup(dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLogin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(lbVisualizacaoDoUsuario)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(dAdicionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbCadastrar)
                    .addComponent(chbAcompanhar)
                    .addComponent(chbConfigurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbAgendamentoPrioritario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbAtenderExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalvar)
                .addContainerGap())
        );

        tbUsuarios.setModel(usuariosTableModel);
        tbUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUsuarios.getTableHeader().setReorderingAllowed(false);
        spTbUsuarios.setViewportView(tbUsuarios);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spTbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btExcluir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spTbUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btEditar)
                    .addComponent(btExcluir))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
       Controller ctrl = Controller.getInstance();
       ctrl.frUsuariosUIBtSalvar(this);
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void chbConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbConfigurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbConfigurarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        Controller.setParentEvt(evt);
        getdAdicionarUsuario().pack();
        getdAdicionarUsuario().setVisible(true);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (getTbUsuarios().getSelectedRowCount()>0) {

            Controller ctrl = Controller.getInstance();
            int line = Math.max(getTbUsuarios().getSelectedRow(), 1);
            
            ctrl.frUsuariosUIBtExcluir(this);
            ctrl.frUsuariosUIRefreshTable(this);
            if (getTbUsuarios().getRowCount()>0) {
               getTbUsuarios().requestFocus();
               getTbUsuarios().setRowSelectionInterval(line-1,line-1);
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (getTbUsuarios().getSelectedRowCount()>0) {

            Controller.setParentEvt(evt);
            Controller ctrl = Controller.getInstance();
            ctrl.frUsuariosUIBtEditar(this);  
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void chbAgendamentoPrioritarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAgendamentoPrioritarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbAgendamentoPrioritarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox chbAcompanhar;
    private javax.swing.JCheckBox chbAgendamentoPrioritario;
    private javax.swing.JCheckBox chbAtenderExcluir;
    private javax.swing.JCheckBox chbCadastrar;
    private javax.swing.JCheckBox chbConfigurar;
    private javax.swing.JDialog dAdicionarUsuario;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbVisualizacaoDoUsuario;
    private javax.swing.JScrollPane spTbUsuarios;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNomeUsuario;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
   private DefaultTableModel usuariosTableModel = new DefaultTableModel();
    /**
     * @return the chbAcompanhar
     */
    public javax.swing.JCheckBox getChbAcompanhar() {
        return chbAcompanhar;
    }

    /**
     * @return the chbCadastrar
     */
    public javax.swing.JCheckBox getChbCadastrar() {
        return chbCadastrar;
    }

    /**
     * @return the chbConfigurar
     */
    public javax.swing.JCheckBox getChbConfigurar() {
        return chbConfigurar;
    }

    /**
     * @return the dAdicionarUsuario
     */
    public javax.swing.JDialog getdAdicionarUsuario() {
        return dAdicionarUsuario;
    }

    /**
     * @return the tbUsuarios
     */
    public javax.swing.JTable getTbUsuarios() {
        return tbUsuarios;
    }

    /**
     * @return the tfLogin
     */
    public javax.swing.JTextField getTfLogin() {
        return tfLogin;
    }

    /**
     * @return the tfNomeUsuario
     */
    public javax.swing.JTextField getTfNomeUsuario() {
        return tfNomeUsuario;
    }

    /**
     * @return the tfSenha
     */
    public javax.swing.JPasswordField getTfSenha() {
        return tfSenha;
    }

    /**
     * @return the usuariosTableModel
     */
    public DefaultTableModel getUsuariosTableModel() {
        return usuariosTableModel;
    }
    
    public int getSelecedUserId() {
        
        int userId;
        int row = getTbUsuarios().getSelectedRow();

        userId = Integer.parseInt(getUsuariosTableModel().
                getValueAt(row, getUsuariosTableModel().findColumn("ID")).
                toString());

        return userId;

    }

    public Usuarios getFormData() {
        
        Usuarios usuario = new Usuarios();
        String permissao = "";

        permissao+=chbAcompanhar.isSelected()?"A":"";
        permissao+=chbCadastrar.isSelected()?"C":"";
        permissao+=chbConfigurar.isSelected()?"F":"";
        permissao+=getChbAgendamentoPrioritario().isSelected()?"P":"";
        permissao+=getChbAtenderExcluir().isSelected()?"E":"";
        
        usuario.setName(tfNomeUsuario.getText());
        usuario.setUsername(tfLogin.getText());
        usuario.setPassword(String.valueOf(tfSenha.getPassword()));
        usuario.setPermissao(permissao);
        
        return usuario;
    }
    
    public void cleanFields() {
        
        tfLogin.setText("");
        tfSenha.setText("");
        tfNomeUsuario.setText("");
        chbAcompanhar.setSelected(false);
        chbConfigurar.setSelected(false);
        chbCadastrar.setSelected(false);
        
    }

    /**
     * @return the chbAgendamentoPrioritario
     */
    public javax.swing.JCheckBox getChbAgendamentoPrioritario() {
        return chbAgendamentoPrioritario;
    }

    /**
     * @return the chbAtenderExcluir
     */
    public javax.swing.JCheckBox getChbAtenderExcluir() {
        return chbAtenderExcluir;
    }
}
