/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import controller.Controller;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Confguiche;
import model.Guiches;

/**
 *
 * @author Diego Dias
 */
public class GuicheUI extends javax.swing.JFrame {

    /**
     * Creates new form GuicheUI
     */
    public GuicheUI() {
        Controller ctrl = Controller.getInstance();
        
        initComponents();
        jpGuiche.setVisible(false);
        jpConfigurar.setVisible(false);
        jpEstatisticas.setVisible(false);
        getBtEstatisticas().setVisible(false);
        getBtConfigurar().setVisible(false);
        for (Guiches guiche : (List<Guiches>) resultGuiches) {
            cbGuicheModel.addElement(guiche.getNome());
        }
        setLocationRelativeTo(null);
        ctrl.frGuicheUICreateTable(this);
        ctrl.frGuicheUIUpdateTable(this);
        ctrl.frGuicheUICreateTableAtendimento(this);
        ctrl.frGuicheUIUpdateTableAtendimento(this);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Controller ctrl = Controller.getInstance();
        emDetran = java.beans.Beans.isDesignTime() ? null : ctrl.ctrlCreateEntityManager().createEntityManager();
        queryGuiches = java.beans.Beans.isDesignTime() ? null : emDetran.createQuery("SELECT g FROM Guiches g");
        resultGuiches = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : queryGuiches.getResultList();
        queryConfGuiches = java.beans.Beans.isDesignTime() ? null : emDetran.createQuery("SELECT c FROM Confguiche c");
        resultConfGuiches = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : queryConfGuiches.getResultList();
        dNovo = new javax.swing.JDialog();
        tfNomeGuiche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rgSom = new javax.swing.ButtonGroup();
        jpConfigurar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfAviso = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jsTempoPermanenciaSenha = new javax.swing.JSpinner();
        jsTamanhoFonteSenha = new javax.swing.JSpinner();
        jsPeriodicidadeConsultaSenha = new javax.swing.JSpinner();
        jsPeriodicidadeConsultaAviso = new javax.swing.JSpinner();
        jsVelocidade = new javax.swing.JSpinner();
        btVoltar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jsTamanhoFonteAviso = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jsUQtdeltimasChamadas = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jsIntervaloRechamadas = new javax.swing.JSpinner();
        jsToleranciaSenha = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jsNtentativasSenha = new javax.swing.JSpinner();
        btNovo = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGuiche = new javax.swing.JTable();
        rbAirp = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        rbIndi = new javax.swing.JRadioButton();
        jpGuiche = new javax.swing.JPanel();
        lbSenha = new javax.swing.JLabel();
        lbNumeroSenha = new javax.swing.JLabel();
        btChamar = new javax.swing.JButton();
        btAtender = new javax.swing.JButton();
        btConfigurar = new javax.swing.JButton();
        btEstatisticas = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lbTotalAtendidas = new javax.swing.JLabel();
        jpLogin = new javax.swing.JPanel();
        tfUsername = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        lbPassword = new javax.swing.JLabel();
        lbFailure = new javax.swing.JLabel();
        cbGuiche = new javax.swing.JComboBox();
        btLogar = new javax.swing.JButton();
        lbGuiche = new javax.swing.JLabel();
        jpEstatisticas = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        dcbDtAtendimento = new datechooser.beans.DateChooserCombo();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAtendimento = new javax.swing.JTable();
        btVoltarEstatisticas = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();

        dNovo.setModal(true);

        tfNomeGuiche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dNovoLayout = new javax.swing.GroupLayout(dNovo.getContentPane());
        dNovo.getContentPane().setLayout(dNovoLayout);
        dNovoLayout.setHorizontalGroup(
            dNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dNovoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dNovoLayout.createSequentialGroup()
                        .addComponent(tfNomeGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dNovoLayout.setVerticalGroup(
            dNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dNovoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guichês Unificados");
        setPreferredSize(new java.awt.Dimension(600, 560));

        jpConfigurar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpConfigurar.setMinimumSize(new java.awt.Dimension(544, 491));

        tfAviso.setToolTipText("Tamanho máximo: 4096 caracteres.");
        jScrollPane2.setViewportView(tfAviso);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Insira avisos (passe o mouse sobre os campos para obter detalhes)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Periodicidade da consulta do aviso:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Periodicidade da consulta da senha:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tempo de permanência (senha):");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tamanho da fonte (senha):");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Velocidade de projeção do aviso.");

        jsTempoPermanenciaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsTempoPermanenciaSenha.setToolTipText("Insira o tempo em segundos de permanencia da senha no painel. Efeito instantâneo!");

        jsTamanhoFonteSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsTamanhoFonteSenha.setToolTipText("Determine o tamanho da fonte da senha e guichê. Efeito instantâneo!");

        jsPeriodicidadeConsultaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsPeriodicidadeConsultaSenha.setToolTipText("Determine (em segundos) o tempo entre consultas ao banco de dados por novas senhas. Necessário reiniciar Painel para ver efeito!");

        jsPeriodicidadeConsultaAviso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsPeriodicidadeConsultaAviso.setToolTipText("Determine (em segundos) o tempo entre consultas ao banco de dados por novos avisos. Necessário reiniciar Painel para ver efeito!");

        jsVelocidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsVelocidade.setToolTipText("Determine a velocidade (em caracteres por segundo) de projeção do aviso de rodapé. Necessário reiniciar Painel para ver efeito!");

        btVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tamanho da fonte do aviso:");

        jsTamanhoFonteAviso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsTamanhoFonteAviso.setToolTipText("Determine o tamanho da fonte do aviso exibido no rodapé do painel. Efeito instantâneo!");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Quantidade de senhas exibidas:");
        jLabel8.setToolTipText("");

        jsUQtdeltimasChamadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsUQtdeltimasChamadas.setToolTipText("Quantidade máxima de senhas exibidas no rodapé na relação de ultimas senhas chamadas. Efeito instantâneo!");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Intervalo entre re-chamadas:");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tempo de tolerância de senha:");
        jLabel11.setToolTipText("");

        jsIntervaloRechamadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsIntervaloRechamadas.setToolTipText("Tempo de espera entre re-chamadas de uma senha sem comparecimento (em minutos). Efeito instantâneo!");

        jsToleranciaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsToleranciaSenha.setToolTipText("Tempo (em minutos) de tolerância decorrido entre a primeira chamada de uma senha (sem comparecimento) até sua invalidação. Efeito instantâneo!");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Chamadas consecutivas:");
        jLabel12.setToolTipText("");

        jsNtentativasSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsNtentativasSenha.setToolTipText("Numero de chamadas consecutivas antes de constatar não comparecimento na primeira chamadas. Efeito instantâneo!");

        btNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btApagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btApagar.setText("Apagar");
        btApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Guichês:");

        tbGuiche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbGuiche.setModel(getGuicheTableModel());
        tbGuiche.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tbGuicheComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tbGuiche);

        rgSom.add(rbAirp);
        rbAirp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbAirp.setText("Airport");
        rbAirp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAirpActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Alerta sonoro:");

        rgSom.add(rbIndi);
        rbIndi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbIndi.setText("Indirimli");

        emDetran.refresh(resultConfGuiches.get(0));
        tfAviso.setText(((Confguiche) resultConfGuiches.get(0)).getAviso());
        jsTempoPermanenciaSenha.setValue(((Confguiche) resultConfGuiches.get(0)).getTexibicao());
        jsPeriodicidadeConsultaAviso.setValue(((Confguiche) resultConfGuiches.get(0)).getTfreqconsultaaviso());
        jsPeriodicidadeConsultaSenha.setValue(((Confguiche) resultConfGuiches.get(0)).getTfreqconsultasenha());
        jsVelocidade.setValue(((Confguiche) resultConfGuiches.get(0)).getVelocidadeaviso());
        jsTamanhoFonteAviso.setValue(((Confguiche) resultConfGuiches.get(0)).getFontaviso());
        jsTamanhoFonteSenha.setValue(((Confguiche) resultConfGuiches.get(0)).getFontsenha());
        jsNtentativasSenha.setValue(((Confguiche) resultConfGuiches.get(0)).getNtentativas());
        jsUQtdeltimasChamadas.setValue(((Confguiche) resultConfGuiches.get(0)).getNultimas());
        jsIntervaloRechamadas.setValue(((Confguiche) resultConfGuiches.get(0)).getIntervalo());
        jsToleranciaSenha.setValue(((Confguiche) resultConfGuiches.get(0)).getTolerancia());
        rbAirp.setSelected(((Confguiche) resultConfGuiches.get(0)).getSound().equals("Airport.wav"));
        rbIndi.setSelected(((Confguiche) resultConfGuiches.get(0)).getSound().equals("Indirimli.wav"));

        javax.swing.GroupLayout jpConfigurarLayout = new javax.swing.GroupLayout(jpConfigurar);
        jpConfigurar.setLayout(jpConfigurarLayout);
        jpConfigurarLayout.setHorizontalGroup(
            jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConfigurarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConfigurarLayout.createSequentialGroup()
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jsNtentativasSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsToleranciaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsIntervaloRechamadas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsUQtdeltimasChamadas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsPeriodicidadeConsultaAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsPeriodicidadeConsultaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsTamanhoFonteAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsTamanhoFonteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsTempoPermanenciaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpConfigurarLayout.createSequentialGroup()
                                .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(jpConfigurarLayout.createSequentialGroup()
                                            .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpConfigurarLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(rbIndi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbAirp)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jpConfigurarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jsIntervaloRechamadas, jsNtentativasSenha, jsPeriodicidadeConsultaAviso, jsPeriodicidadeConsultaSenha, jsTamanhoFonteAviso, jsTamanhoFonteSenha, jsTempoPermanenciaSenha, jsToleranciaSenha, jsUQtdeltimasChamadas, jsVelocidade});

        jpConfigurarLayout.setVerticalGroup(
            jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConfigurarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jsTempoPermanenciaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConfigurarLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btNovo)
                            .addComponent(btApagar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbIndi)
                            .addComponent(rbAirp)))
                    .addGroup(jpConfigurarLayout.createSequentialGroup()
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jsTamanhoFonteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsTamanhoFonteAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsPeriodicidadeConsultaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jsPeriodicidadeConsultaAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jsVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jsUQtdeltimasChamadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jsIntervaloRechamadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConfigurarLayout.createSequentialGroup()
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jsToleranciaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsNtentativasSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jpConfigurarLayout.createSequentialGroup()
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVoltar)))
                .addContainerGap())
        );

        jpGuiche.setEnabled(false);
        jpGuiche.setMaximumSize(new java.awt.Dimension(413, 287));
        jpGuiche.setPreferredSize(new java.awt.Dimension(413, 287));

        lbSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSenha.setText("Senha:");

        lbNumeroSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNumeroSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNumeroSenha.setMaximumSize(new java.awt.Dimension(30, 22));
        lbNumeroSenha.setMinimumSize(new java.awt.Dimension(30, 22));
        lbNumeroSenha.setName("SenhaID"); // NOI18N
        lbNumeroSenha.setPreferredSize(new java.awt.Dimension(30, 22));

        btChamar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btChamar.setText("Chamar");
        btChamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChamarActionPerformed(evt);
            }
        });

        btAtender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAtender.setText("Atender");
        btAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtenderActionPerformed(evt);
            }
        });

        btConfigurar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btConfigurar.setText("Configurar");
        btConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfigurarActionPerformed(evt);
            }
        });

        btEstatisticas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btEstatisticas.setText("Estatisticas");
        btEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstatisticasActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Atendidas:");

        lbTotalAtendidas.setMaximumSize(new java.awt.Dimension(30, 22));
        lbTotalAtendidas.setMinimumSize(new java.awt.Dimension(30, 22));
        lbTotalAtendidas.setPreferredSize(new java.awt.Dimension(30, 22));

        javax.swing.GroupLayout jpGuicheLayout = new javax.swing.GroupLayout(jpGuiche);
        jpGuiche.setLayout(jpGuicheLayout);
        jpGuicheLayout.setHorizontalGroup(
            jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGuicheLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGuicheLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpGuicheLayout.createSequentialGroup()
                        .addGroup(jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btConfigurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpGuicheLayout.createSequentialGroup()
                                .addGroup(jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSenha)
                                    .addComponent(btChamar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNumeroSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btAtender, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jpGuicheLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(lbTotalAtendidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(113, 113, 113))))
        );
        jpGuicheLayout.setVerticalGroup(
            jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGuicheLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSenha)
                    .addComponent(lbNumeroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(lbTotalAtendidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChamar)
                    .addComponent(btAtender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConfigurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEstatisticas)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tfUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        tfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUsernameKeyPressed(evt);
            }
        });

        lbUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbUsername.setText("Usuário:");

        tfPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        lbPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPassword.setText("Senha:");

        lbFailure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFailure.setText(" ");

        cbGuiche.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbGuiche.setModel(cbGuicheModel);

        btLogar.setText("Logar");
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });

        lbGuiche.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbGuiche.setText("Guichê:");

        javax.swing.GroupLayout jpLoginLayout = new javax.swing.GroupLayout(jpLogin);
        jpLogin.setLayout(jpLoginLayout);
        jpLoginLayout.setHorizontalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGuiche)
                    .addComponent(lbPassword)
                    .addComponent(lbUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFailure, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jpLoginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btLogar, cbGuiche, tfPassword, tfUsername});

        jpLoginLayout.setVerticalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGuiche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFailure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLogar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Atendimento por Guiche");

        dcbDtAtendimento.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
        dcbDtAtendimento.setLocale(new java.util.Locale("pt", "BR", ""));
        dcbDtAtendimento.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        dcbDtAtendimento.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dcbDtAtendimentoOnSelectionChange(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Data:");

        tbAtendimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbAtendimento.setModel(getAtendimentoTableModel());
        jScrollPane3.setViewportView(tbAtendimento);

        btVoltarEstatisticas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btVoltarEstatisticas.setText("Voltar");
        btVoltarEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarEstatisticasActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEstatisticasLayout = new javax.swing.GroupLayout(jpEstatisticas);
        jpEstatisticas.setLayout(jpEstatisticasLayout);
        jpEstatisticasLayout.setHorizontalGroup(
            jpEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstatisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEstatisticasLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpEstatisticasLayout.createSequentialGroup()
                        .addGroup(jpEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                            .addGroup(jpEstatisticasLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcbDtAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btVoltarEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jpEstatisticasLayout.setVerticalGroup(
            jpEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstatisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dcbDtAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(jpEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btVoltarEstatisticas)
                        .addComponent(btAtualizar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jpConfigurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 77, Short.MAX_VALUE)
                    .addComponent(jpGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 77, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(115, 115, 115)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpConfigurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 113, Short.MAX_VALUE)
                    .addComponent(jpGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 113, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(jpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(140, 140, 140)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        getJpConfigurar().setVisible(false);
        getJpGuiche().setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed
    
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frGuicheUIBtSalvar(this);
    }//GEN-LAST:event_btSalvarActionPerformed
    
    private void btChamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChamarActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frGuicheUIBtChamar(this);
    }//GEN-LAST:event_btChamarActionPerformed
    
    private void btAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtenderActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frGuicheUIBtAtender(this);
        ctrl.frGuicheUIUpdateNumAtendidas(this);
    }//GEN-LAST:event_btAtenderActionPerformed
    
    private void btConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfigurarActionPerformed
        getJpGuiche().setVisible(false);
        getJpConfigurar().setVisible(true);
    }//GEN-LAST:event_btConfigurarActionPerformed
    
    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        getTfPassword().requestFocus();
    }//GEN-LAST:event_tfUsernameActionPerformed
    
    private void tfUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsernameKeyPressed
    }//GEN-LAST:event_tfUsernameKeyPressed
    
    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frGuicheUIBtLogar(this);
    }//GEN-LAST:event_tfPasswordActionPerformed
    
    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frGuicheUIBtLogar(this);
    }//GEN-LAST:event_btLogarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frGuicheUIBtNovo(this);
    }//GEN-LAST:event_btNovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Controller ctrl = Controller.getInstance();
       ctrl.frGuicheUIBtSalvarNovoGuiche(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarActionPerformed
       if (getTbGuiche().getSelectedRowCount()>0){
          Controller ctrl = Controller.getInstance();
          ctrl.frGuicheUIBtApagarGuiche(this);
       }
    }//GEN-LAST:event_btApagarActionPerformed

    private void tbGuicheComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tbGuicheComponentShown

    }//GEN-LAST:event_tbGuicheComponentShown

    private void btEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstatisticasActionPerformed
        getJpGuiche().setVisible(false);
        getJpEstatisticas().setVisible(true);
    }//GEN-LAST:event_btEstatisticasActionPerformed

    private void dcbDtAtendimentoOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dcbDtAtendimentoOnSelectionChange
        Controller ctrl = Controller.getInstance();
        ctrl.frGuicheUIUpdateTableAtendimento(this);
    }//GEN-LAST:event_dcbDtAtendimentoOnSelectionChange

    private void btVoltarEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarEstatisticasActionPerformed
        getJpEstatisticas().setVisible(false);
        getJpGuiche().setVisible(true);
    }//GEN-LAST:event_btVoltarEstatisticasActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        Controller ctrl = Controller.getInstance();
        ctrl.frGuicheUIUpdateTableAtendimento(this);
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void rbAirpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAirpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAirpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuicheUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuicheUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuicheUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuicheUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuicheUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btAtender;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btChamar;
    private javax.swing.JButton btConfigurar;
    private javax.swing.JButton btEstatisticas;
    private javax.swing.JButton btLogar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btVoltarEstatisticas;
    private javax.swing.JComboBox cbGuiche;
    private javax.swing.JDialog dNovo;
    private datechooser.beans.DateChooserCombo dcbDtAtendimento;
    private javax.persistence.EntityManager emDetran;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpConfigurar;
    private javax.swing.JPanel jpEstatisticas;
    private javax.swing.JPanel jpGuiche;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JSpinner jsIntervaloRechamadas;
    private javax.swing.JSpinner jsNtentativasSenha;
    private javax.swing.JSpinner jsPeriodicidadeConsultaAviso;
    private javax.swing.JSpinner jsPeriodicidadeConsultaSenha;
    private javax.swing.JSpinner jsTamanhoFonteAviso;
    private javax.swing.JSpinner jsTamanhoFonteSenha;
    private javax.swing.JSpinner jsTempoPermanenciaSenha;
    private javax.swing.JSpinner jsToleranciaSenha;
    private javax.swing.JSpinner jsUQtdeltimasChamadas;
    private javax.swing.JSpinner jsVelocidade;
    private javax.swing.JLabel lbFailure;
    private javax.swing.JLabel lbGuiche;
    private javax.swing.JLabel lbNumeroSenha;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTotalAtendidas;
    private javax.swing.JLabel lbUsername;
    private javax.persistence.Query queryConfGuiches;
    private javax.persistence.Query queryGuiches;
    private javax.swing.JRadioButton rbAirp;
    private javax.swing.JRadioButton rbIndi;
    private java.util.List resultConfGuiches;
    private java.util.List resultGuiches;
    private javax.swing.ButtonGroup rgSom;
    private javax.swing.JTable tbAtendimento;
    private javax.swing.JTable tbGuiche;
    private javax.swing.JTextPane tfAviso;
    private javax.swing.JTextField tfNomeGuiche;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel cbGuicheModel = new DefaultComboBoxModel();
    private DefaultTableModel guicheTableModel = new DefaultTableModel();
    private DefaultTableModel atendimentoTableModel = new DefaultTableModel();
    
    /**
     * @return the btConfigurar
     */
    public javax.swing.JButton getBtConfigurar() {
        return btConfigurar;
    }

    /**
     * @return the cbGuiche
     */
    public javax.swing.JComboBox getCbGuiche() {
        return cbGuiche;
    }

    /**
     * @return the emDetran
     */
    public javax.persistence.EntityManager getEmDetran() {
        return emDetran;
    }

    /**
     * @return the jpConfigurar
     */
    public javax.swing.JPanel getJpConfigurar() {
        return jpConfigurar;
    }

    /**
     * @return the jpGuiche
     */
    public javax.swing.JPanel getJpGuiche() {
        return jpGuiche;
    }

    /**
     * @return the jpLogin
     */
    public javax.swing.JPanel getJpLogin() {
        return jpLogin;
    }

    /**
     * @return the jsIntervaloRechamadas
     */
    public javax.swing.JSpinner getJsIntervaloRechamadas() {
        return jsIntervaloRechamadas;
    }

    /**
     * @return the jsNtentativasSenha
     */
    public javax.swing.JSpinner getJsNtentativasSenha() {
        return jsNtentativasSenha;
    }

    /**
     * @return the jsPeriodicidadeConsultaSenha
     */
    public javax.swing.JSpinner getJsPeriodicidadeConsultaSenha() {
        return jsPeriodicidadeConsultaSenha;
    }

    /**
     * @return the jsTamanhoFonteAviso
     */
    public javax.swing.JSpinner getJsTamanhoFonteAviso() {
        return jsTamanhoFonteAviso;
    }

    /**
     * @return the jsTamanhoFonteSenha
     */
    public javax.swing.JSpinner getJsTamanhoFonteSenha() {
        return jsTamanhoFonteSenha;
    }

    /**
     * @return the jsTempoPermanenciaSenha
     */
    public javax.swing.JSpinner getJsTempoPermanenciaSenha() {
        return jsTempoPermanenciaSenha;
    }

    /**
     * @return the jsToleranciaSenha
     */
    public javax.swing.JSpinner getJsToleranciaSenha() {
        return jsToleranciaSenha;
    }

    /**
     * @return the jsUQtdeltimasChamadas
     */
    public javax.swing.JSpinner getJsUQtdeltimasChamadas() {
        return jsUQtdeltimasChamadas;
    }

    /**
     * @return the jsVelocidade
     */
    public javax.swing.JSpinner getJsVelocidade() {
        return jsVelocidade;
    }

    /**
     * @return the lbFailure
     */
    public javax.swing.JLabel getLbFailure() {
        return lbFailure;
    }

    /**
     * @return the lbGuiche
     */
    public javax.swing.JLabel getLbGuiche() {
        return lbGuiche;
    }

    /**
     * @return the lbNumeroSenha
     */
    public javax.swing.JLabel getLbNumeroSenha() {
        return lbNumeroSenha;
    }

    /**
     * @return the lbPassword
     */
    public javax.swing.JLabel getLbPassword() {
        return lbPassword;
    }

    /**
     * @return the lbSenha
     */
    public javax.swing.JLabel getLbSenha() {
        return lbSenha;
    }

    /**
     * @return the lbUsername
     */
    public javax.swing.JLabel getLbUsername() {
        return lbUsername;
    }

    /**
     * @return the tfAviso
     */
    public javax.swing.JTextPane getTfAviso() {
        return tfAviso;
    }

    /**
     * @return the tfPassword
     */
    public javax.swing.JPasswordField getTfPassword() {
        return tfPassword;
    }

    /**
     * @return the tfUsername
     */
    public javax.swing.JTextField getTfUsername() {
        return tfUsername;
    }

    /**
     * @return the jsPeriodicidadeConsultaAviso
     */
    public javax.swing.JSpinner getJsPeriodicidadeConsultaAviso() {
        return jsPeriodicidadeConsultaAviso;
    }

    /**
     * @return the tfNomeGuiche
     */
    public javax.swing.JTextField getTfNomeGuiche() {
        return tfNomeGuiche;
    }

    /**
     * @return the dNovo
     */
    public javax.swing.JDialog getdNovo() {
        return dNovo;
    }

    /**
     * @return the queryConfGuiches
     */
    public javax.persistence.Query getQueryConfGuiches() {
        return queryConfGuiches;
    }

    /**
     * @return the queryGuiches
     */
    public javax.persistence.Query getQueryGuiches() {
        return queryGuiches;
    }

    /**
     * @return the resultConfGuiches
     */
    public java.util.List getResultConfGuiches() {
        return resultConfGuiches;
    }

    /**
     * @return the resultGuiches
     */
    public java.util.List getResultGuiches() {
        return resultGuiches;
    }

    /**
     * @return the cbGuicheModel
     */
    public DefaultComboBoxModel getCbGuicheModel() {
        return cbGuicheModel;
    }

    /**
     * @param queryGuiches the queryGuiches to set
     */
    public void setQueryGuiches(javax.persistence.Query queryGuiches) {
        this.queryGuiches = queryGuiches;
    }

    /**
     * @param resultGuiches the resultGuiches to set
     */
    public void setResultGuiches(java.util.List resultGuiches) {
        this.resultGuiches = resultGuiches;
    }

    /**
     * @return the guicheTableModel
     */
    public DefaultTableModel getGuicheTableModel() {
        return guicheTableModel;
    }

    /**
     * @return the tbGuiche
     */
    public javax.swing.JTable getTbGuiche() {
        return tbGuiche;
    }

    /**
     * @return the tbAtendimento
     */
    public javax.swing.JTable getTbAtendimento() {
        return tbAtendimento;
    }

    /**
     * @return the atendimentoTableModel
     */
    public DefaultTableModel getAtendimentoTableModel() {
        return atendimentoTableModel;
    }

    /**
     * @return the btApagar
     */
    public javax.swing.JButton getBtApagar() {
        return btApagar;
    }

    /**
     * @return the btAtender
     */
    public javax.swing.JButton getBtAtender() {
        return btAtender;
    }

    /**
     * @return the btChamar
     */
    public javax.swing.JButton getBtChamar() {
        return btChamar;
    }

    /**
     * @return the btLogar
     */
    public javax.swing.JButton getBtLogar() {
        return btLogar;
    }

    /**
     * @return the btNovo
     */
    public javax.swing.JButton getBtNovo() {
        return btNovo;
    }

    /**
     * @return the btSalvar
     */
    public javax.swing.JButton getBtSalvar() {
        return btSalvar;
    }

    /**
     * @return the btVoltar
     */
    public javax.swing.JButton getBtVoltar() {
        return btVoltar;
    }

    /**
     * @return the dcbDtAtendimento
     */
    public datechooser.beans.DateChooserCombo getDcbDtAtendimento() {
        return dcbDtAtendimento;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel10
     */
    public javax.swing.JLabel getjLabel10() {
        return jLabel10;
    }

    /**
     * @return the jLabel11
     */
    public javax.swing.JLabel getjLabel11() {
        return jLabel11;
    }

    /**
     * @return the jLabel12
     */
    public javax.swing.JLabel getjLabel12() {
        return jLabel12;
    }

    /**
     * @return the jLabel13
     */
    public javax.swing.JLabel getjLabel13() {
        return jLabel13;
    }

    /**
     * @return the jLabel14
     */
    public javax.swing.JLabel getjLabel14() {
        return jLabel14;
    }

    /**
     * @return the jLabel16
     */
    public javax.swing.JLabel getjLabel16() {
        return jLabel16;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @return the jLabel6
     */
    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @return the jLabel8
     */
    public javax.swing.JLabel getjLabel8() {
        return jLabel8;
    }

    /**
     * @return the jLabel9
     */
    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return getJpEstatisticas();
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @return the jScrollPane3
     */
    public javax.swing.JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    /**
     * @return the btEstatisticas
     */
    public javax.swing.JButton getBtEstatisticas() {
        return btEstatisticas;
    }

    /**
     * @return the jpEstatisticas
     */
    public javax.swing.JPanel getJpEstatisticas() {
        return jpEstatisticas;
    }

    /**
     * @return the btVoltarEstatisticas
     */
    public javax.swing.JButton getBtVoltarEstatisticas() {
        return btVoltarEstatisticas;
    }

    /**
     * @return the jLabel15
     */
    public javax.swing.JLabel getjLabel15() {
        return jLabel15;
    }

    /**
     * @return the lbTotalAtendidas
     */
    public javax.swing.JLabel getLbTotalAtendidas() {
        return lbTotalAtendidas;
    }

    /**
     * @return the btAtualizar
     */
    public javax.swing.JButton getBtAtualizar() {
        return btAtualizar;
    }

    /**
     * @return the jLabel17
     */
    public javax.swing.JLabel getjLabel17() {
        return jLabel17;
    }

    /**
     * @return the rbAirp
     */
    public javax.swing.JRadioButton getRbAirp() {
        return rbAirp;
    }


    /**
     * @return the rbIndi
     */
    public javax.swing.JRadioButton getRbIndi() {
        return rbIndi;
    }

    /**
     * @return the rgSom
     */
    public javax.swing.ButtonGroup getRgSom() {
        return rgSom;
    }
}
